image: composer:latest

stages:
  - lint

cache:
  paths:
    - vendor/

before_script:
  - composer install

composer-validate:
  stage: lint
  script:
    - composer validate
  tags:
    - docker

php-lint:
  stage: lint
  script:
    - cd apnsframework
    - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep -v "No syntax errors detected"; then exit 1; fi
  tags:
    - docker

php-lint-examples:
  stage: lint
  script:
    - cd examples
    - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep -v "No syntax errors detected"; then exit 1; fi
  tags:
    - docker
  allow_failure: true
